config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'sessions/new'

  get 'user/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get  '/cities',  to: 'application#cities'
  delete '/logout',  to: 'sessions#destroy'

  get '/markets/:id/reviews', to: 'markets#ajax_reviews'
  get '/markets/:id/stores', to: 'markets#ajax_stores'
  get '/stores/:id/reviews', to: 'stores#ajax_reviews'
  get '/stores/:id/products', to: 'stores#ajax_products'
  get '/stores/new/markets', to: 'stores#ajax_search_markets'

  post '/market_images', to: 'market_image#ajax_create'
  post '/store_images', to: 'store_image#ajax_create'
  post '/product_images', to: 'product_image#ajax_create'

  delete '/market_images/:id', to: 'market_image#ajax_destory'
  delete '/store_images/:id', to: 'store_image#ajax_destory'
  delete '/product_images/:id', to: 'product_image#ajax_destory'

  get '/markets/:id/store_market_relationships/new', to: 'store_market_relationships#new'

  get '/search', to: 'searches#index'
  get '/users/:id/edit', to: 'users#edit'
  get '/users/:id/change_password', to: 'users#change_password', as: 'change_password'


  get '/users/:id/shopping_list', to: 'users#shopping_list', as: 'shopping_list'
  get '/users/:id/requests', to: 'users#requests', as: 'user_requests'
  get '/users/:id/markets', to: 'users#markets', as: 'user_markets'
  get '/users/:id/reviews', to: 'users#reviews', as: 'user_reviews'
  get '/users/:id/store/new', to: 'users#bevendor', as: 'bevendor'

  patch '/users/:id/update_password', to: 'users#update_password'

  get '/search/heroku', to: 'application#heroku'

  %w(404 422 500).each do |code|
    get code, to: "application#error", code: code
  end

  resources :subscriptions

  resources :markets do
    resources :stores
    resources :market_reviews
  end

  resources :stores do
    resources :products
    resources :store_reviews
  end

  resources :users do
    resources :shopping_lists
    resources :markets
    resources :store_reviews
    resources :market_reviews
    resources :requests
  end

  resources :stores do
    resources :subscriptions
  end

  resources :products do
    resources :shopping_lists
  end

  resources :shopping_lists
  resources :stores
  resources :vendors
  resources :users
  resources :market_reviews
  resources :store_reviews
  resources :store_market_relationships
  resources :requests
  resources :products

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_one :vendor
  has_many :subscriptions,:dependent => :destroy
  has_many :store_reviews,:dependent => :destroy
  has_many :market_reviews,:dependent => :destroy
  has_many :markets,:dependent => :destroy
  has_many :shopping_lists, :dependent => :destroy
  has_many :requests, :through => :markets,:dependent => :destroy


  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    length: { maximum: 50 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

   has_secure_password
   validates :password, presence: true, length: { minimum: 6 }
	 validates :zipcode, presence: true, length: { is: 5 }

   def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :update_password, :markets, :change_password,:requests, :reviews, :shopping_list]
  before_action :require_login, only: [:edit, :update, :show,:change_password,:update_password, :update,:markets,:requests,:reviews]
  before_action :user_shopping_list, only: [:show, :shopping_list]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    render :show, locals: { user: @user = @user, board: board = "dashboard",item: @items}
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    render :show, locals: { user: @user = current_user, board: board = "edit"}
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_reset_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :show, locals: { user: @user, board: board = "edit"} }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_password
    @user = User.find(params[:id])
    if @user &&  @user.authenticate(params[:user][:old_password])
      if @user.update(user_reset_password_params)
        redirect_to @user, notice: 'Password was successfully changed.'
      else
        render :show, locals: { user: @user, board: board = "change_password"}
      end
    else
      @user.errors.add(:password, "Password Wrong")
      render :show, locals: { user: @user, board: board = "change_password"}
    end
  end

  def change_password
    render :show, locals: { user: @user = @user, board: board = "change_password"}
  end


  def shopping_list
    if params[:date].nil? || params[:hour1].nil? || params[:hour2].nil?
      time = (Time.now.wday-1) * 86400 + Time.now.hour * 3600 + Time.now.min * 60
      @hour1 = time
      @hour2 = time
      @schedule = getList(time, time)
    else
     @valid = !params[:date].empty? && !params[:hour1].empty? && !params[:hour2].empty?
      if @valid
        @hour1 = to_timestamp(params[:date], params[:hour1])
        @hour2 = to_timestamp(params[:date], params[:hour2])
        if @hour2 >= @hour1
          @schedule = getList(@hour1, @hour2)
        end
      else
        time = (Time.now.wday-1) * 86400 + Time.now.hour * 3600 + Time.now.min * 60
        @hour1 = time
        @hour2 = time
        @schedule = getList(time, time)
      end
    end
    render :show, locals: { user: @user = @user, board: board = "shopping_list", item: @items }
  end

  def markets
    render :show, locals: { user: @user = @user, board: board = "markets"}
  end

  def reviews
    render :show, locals: { user: @user = @user, board: board = "reviews"}
  end

  def requests
    render :show, locals: { user: @user = @user, board: board = "requests"}
  end

  def bevendor
    render :show, locals: { user: @user = @user, board: board = "bevendor"}
  end

  private

    def getMarketsAvailable(hour1, hour2)
      markets = []
      Market.all.each do |mkt|
        if mkt.close_time > hour1 && mkt.open_time < hour2
          markets.push(mkt)
        end
      end
      return markets
    end

    def getMarketProducts(markets)
      marketproducts = Hash.new
      #make an empty array to contain all products for each market using a HT
      markets.each do |mkt|
        marketproducts[mkt] = []
      end
      #fill each array in each hash
      markets.each do |mkt|
        #go through each store in each market
        mkt.stores.each do |str|
          str.products.each do |pdt|
            marketproducts[mkt].push(pdt)
          end
        end
      end
      return marketproducts
    end

    def getList(hour1, hour2)
      @list = Hash.new
      @schedule = Hash.new
      @marketproducts = getMarketProducts(getMarketsAvailable(hour1, hour2)) #HT with market => products

      if @marketproducts.empty?
        return @schedule
      end

      #search through all markets
      @marketproducts.each do |mkt, products|
        @schedule[mkt] = Hash.new
        #search through the list
        ShoppingList.where(:user_id => @user.id).each do |item|
        #search through all products at the market for each item in the shopping list
          #if items are nominally similar, for now eql works because of the way the data is seeded but for improvement there should be a feature to have different comparison styles
          products.each do |prod|
            if prod.name.eql? item.product.name
              if @list[item].nil?
                @list[item] = prod
                #replace the existing item if another item is more popular
              elsif !prod.popularity.nil? and !@list[item].popularity.nil?
                if @list[item].popularity < prod.popularity
                @list[item] = prod
                end
              end
            end
          end
        end

        @list.each do |s_item, item|
          if @schedule[mkt][item.store].nil?
            @schedule[mkt][item.store] = [item]
          else
            @schedule[mkt][item.store].push(item)
          end
        end
        @list = Hash.new
      end
      return @schedule
    end

    def user_shopping_list
      @schedule = {:date => "", :hour1 => "", :hour2 => ""}
      @meats = []
      @grains = []
      @vegetables = []
      @fruits = []
      @misc = []
      @items = [@vegetables, @fruit, @grains, @meats, @misc]
      ShoppingList.where(:user_id => @user.id).each do |item|
        if item.product.group.eql? "Vegetable"
          @vegetables.push(item)
        elsif item.product.group.eql? "Fruit"
          @fruits.push(item)
        elsif item.product.group.eql? "Grain"
          @grains.push(item)
        elsif item.product.group.eql? "Meat"
          @meats.push(item)
        else item.product.group.eql? "Misc."
          @misc.push(item)
        end
      end
    end

    def to_timestamp(date, hour)
      (hour_hash[hour]*3600+day_hash[date]*86400)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation,
                        :zipcode)
    end

    def user_reset_params
      params.require(:user).permit(:name,:zipcode)
    end

    def user_reset_password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 500)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/users/_change_password.html.erb
<div class="row well">
<h1 class="text-center">Change Password</h1>
<%= form_for user, :url => url_for(:controller => 'users', :action => 'update_password') do |f|%>
<%= render 'shared/hint_messages', object: user %></br>
<div class="form-group">
  <div class="field">
    <%= f.label :old_password %>
    <%= f.password_field :old_password, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
</div>

<div class="actions">
  <%= f.submit "Reset Password", class: "btn btn-danger col-sm-12" %>
</div>
<% end %>
</div>

app/views/users/_dashboard.html.erb
 <% if @user.id == current_user.id %>
<%= render  partial: "requests", locals: { user: @user = @user} %>
<% end %>
<%= render  partial: "markets", locals: { user: @user} %>
<%= render  partial: "reviews", locals: { user: @user} %>

app/views/users/_form_edit.html.erb
<div class="row well">
<h1 class="text-center">Change Account Information</h1>
<%= form_for user, :url => url_for(:controller => 'users', :action => 'update') do |f|%>
<%= render 'shared/hint_messages', object: user %></br>
<div class="form-group">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <%= f.label :zipcode, "Zipcode" %>
    <%= f.text_field :zipcode, class: "form-control" %>
  </div>
</div>

<div class="actions">
  <%= f.submit "Updata Information", class: "btn btn-primary col-sm-12" %>
</div>
<% end %>
</div>

app/views/users/_form_new.html.erb
<%= form_for(user) do |f| %>
<%= render 'shared/hint_messages', object: user %></br>
<div class="form-group">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <%= f.label :zipcode, "Zipcode" %>
    <%= f.text_field :zipcode, class: "form-control" %>
  </div>
</div>

<div class="actions">
  <%= f.submit "Create My Account", class: "btn btn-primary col-sm-5" %>
  <%= link_to "Cancel and Go Back", root_path, class: 'btn btn-danger col-sm-5 col-sm-offset-2' %>
</div>
<% end %>

<p>
  <br>
  </br>
  <center>
<span class="a-padding">Already Have an Account? <%= link_to "Log In Now", sessions_new_path, class: 'a-padding' %></span>
  </center>
</p>

app/views/users/_markets.html.erb
<% if @user.markets.length > 0%>
<div class="row well">
  <div class="col-sm-12">
    <h3 class="text-center">User's Markets</h3>
      <%= render 'shared/markets_panel_lg', locals: { markets: @markets = @user.markets } %>
  </div>
</div>
<% end %>

<% if isVendor(@user) and @user.vendor.store.markets.length > 0 %>
<div class="row">
  <div class="col-sm-12 well">
    <h3 class="text-center">User Store's Markets</h3>
    <%= render 'shared/markets_panel', locals: { markets: @markets = @user.vendor.store.markets } %>
  </div>
</div>
<% end %>

app/views/users/_requests.html.erb
<div class="row well">
<div class="col-sm-12 panel-custom-md">
  <%= render 'shared/empty_messages', locals: { objects: @objects = @user.requests.where(:status => 0), class: @class = "Pending Requests" } %>
  <% if @user.requests.where(:status => 0).count > 0 %>
  <h1 class="text-center">Pending Application</h1>
  <table class="table table-striped table-hover">
    <thead class="thead-inverse text-center">
      <tr>
        <th>Status</th>
        <th>Market</th>
        <th>Store</th>
        <th>Owner</th>
        <th>Time</th>
        <th colspan="3"></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @user.requests.where(:status => 0).order('created_at DESC').each do |request| %>
      <% if request.status == 0 or request.status == 1%>
        <tr>
          <td class="col-md-2">
            <% if request.status == 0 %>
            <div class="label label-warning"><%= translate_status_to_market_owner(request.status) %><div>
            <% else %>
            <div class="label label-default"><%= translate_status_to_market_owner(request.status) %><div>
            <% end %>
          </td>
          <td class="col-md-2"><%= link_to request.market.name[0..10], request.market%></td>
          <td class="col-md-2"><%= link_to request.store.name[0..10], request.store%></td>
          <td class="col-md-2"><%= link_to request.store.vendor.user.name[0..10], request.store.vendor.user%></td>
          <td class="col-md-2"><%= request.created_at.strftime("%d %b. %Y") %></td>
          <td class="col-md-1">
            <%= form_for request, :method => :patch do |f|%>
            <%= f.hidden_field :status, :value => "1" %>
            <%= f.submit "Accept", class: "btn btn-primary" %>
            <% end %>
          </td>
          <td class="col-md-1">
            <%= form_for request,method: :patch do |f|%>
            <%= f.hidden_field :status,:value => "2" %>
            <%= f.submit "Refuse", class: "btn btn-default" ,data: {confirm: t('messages.Are you sure Refuse the application'), ok: t('buttons.Sure'), cancel: t('buttons.cancel') } %>
            <% end %>
          </td>
        </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>
  <% end %>
</div>
</div>

app/views/users/_responsed_requests.html.erb
<div class="row well">
<div class="col-sm-12 panel-custom-md">
  <%= render 'shared/empty_messages', locals: { objects: @objects = @user.requests.where(:status => [1,2]), class: @class = "Unresponsed Request" } %>
  <% if @user.requests.where(:status => [1,2]).count > 0 %>
  <h1 class="text-center">Responsed Application</h1>
  <table class="table table-striped table-hover">
    <thead class="thead-inverse text-center">
      <tr>
        <th>Status</th>
        <th>Market</th>
        <th>Store</th>
        <th>Owner</th>
        <th>Time</th>
      </tr>
    </thead>

    <tbody>
      <% @user.requests.where(:status => [1,2]).order('updated_at DESC').each do |request| %>
      <% if request.status == 1 or request.status == 2%>
        <tr>
          <% if request.status == 1 %>
          <td class="col-md-2"><div class="label label-success"><%= translate_status_to_market_owner(request.status) %><div></td>
          <% elsif  request.status == 2%>
          <td class="col-md-2"><div class="label label-danger"><%= translate_status_to_market_owner(request.status) %><div></td>
          <% end %>
          <td class="col-md-2"><%= link_to request.market.name[0..10], request.market%></td>
          <td class="col-md-2"><%= link_to request.store.name[0..10], request.store%></td>
          <td class="col-md-2"><%= link_to request.store.vendor.user.name[0..10], request.store.vendor.user%></td>
          <td class="col-md-2"><%= request.updated_at %></th>
        </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>
  <% end %>
</div>
</div>

app/views/users/_shopping_list.html.erb
<div class="row ">
  	  <center><h1>Shopping Schedule Generator</h1></center>
  		<%= form_tag(shopping_list_path, method: "get") do %>
  		  <div class="col-md-12 text-center">
          <%= label_tag(:date, "I want to go shopping on") %>
          <%= select_tag(:date, options_for_select(["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]), {:include_blank => true})%>
          <%= label_tag(:hour1, "sometime between") %>
    			<%= select_tag(:hour1, options_for_select(["10AM", "11AM", "12PM", "1PM", "2PM", "3PM", "4PM", "5PM", "6PM", "7PM"]), {:include_blank => true})%>
          <%= label_tag(:hour2, "and") %>
          <%= select_tag(:hour2, options_for_select(["11AM", "12PM", "1PM", "2PM", "3PM", "4PM", "5PM", "6PM", "7PM", "8PM"]), {:include_blank => true})%>
    			<%= submit_tag(name="Submit") %>
  		  </div>
  		<% end %>
</div>

<div class="row">
<div class="col-sm-5 panel-custom-md">
  <h3 class="text-center">Your Shopping List</h2>
    <% @items.each do |a| %>
      <% if !a.nil? %>
        <% if a.any? %>
      <h4 class="text-center"><%=a.first.product.group%></h4>
      <table class="table table-striped table-hover">
        <thead class="thead-inverse text-center">
          <tr>
            <th>Item</th>
            <th>Date Added</th>
            <th>Delete Item</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% a.each do |item| %>
            <tr id="<%= item.id%>">
              <td class="col-md-5 text-left">
                <%=item.product.name %>
              </td>
              <td>
                <%=item.created_at.to_s[0..10]%>
              </td>
              <td>
                <button type="button" class="btn btn-danger delShoppingList" value="<%=item.id%>">Delete</button>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% end %>
      <% end %>
    <% end %>
</div>

<div class="col-sm-1"></div>
<div class="col-sm-6 panel-custom-md">
  <h3 class="text-center">Your Shopping Schedule</h2>
      <% if @hour2 < @hour1%>
        The time range you chose does not make sense. Please try again.
      <% else %>
        <% if @schedule.empty?%>
          Sorry! But there no stores at the time with the products in your shopping list
        <% else %>
          <% @schedule.each do |mkt, stores|%>
              <b>----------------------------------------------------------<br></b>
              <b>Market:</b>&nbsp&nbsp&nbsp&nbsp<%=mkt.name%><br>
              <b>Address: </b><%=mkt.address%>, <br>
              &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
              <%=mkt.city%>, <%=mkt.state%> <%=mkt.zipcode%><br>
              <b>Hours:</b>&nbsp&nbsp&nbsp&nbsp&nbsp<%=get_time_from_timestamp(mkt.open_time)%> - <%=get_time_from_timestamp(mkt.close_time)%> <br>
              <b>-----------------------------------------------------------</b><br>
            <% stores.each do |store, products| %>
              <b><%= store.name%>:</b><br>
                <% products.each do |prod| %>
                  <%=prod.name %><br>
                  <%if products[-1].eql? prod%>
                    <br>
                  <% end %>
                <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>

</div>
</div>

<script>
$(".delShoppingList").click(function() {
  var btn = $(this);
  $.ajax({
    url: "/shopping_lists/" +  btn.attr('value'),
    dataType: "json",
    type: "DELETE",
    success: function(data, success) {
      alert("Deleted Successfully");
    },
    error: function(data, failure) {
      alert("Something wrong happened, Please try again later");
    }
  });
});
</script>

app/views/users/edit.html.erb
<h1>Editing User</h1>1
<%= render 'form_edit', user: @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Users</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Zipcode</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.zipcode %></td>
        <td><%= user.city %></td>
        <td><%= user.state %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="board-md row ">
	<h1 class="text-center">Sign up</h1>
	<div class="well col-md-6 col-md-offset-3">
			<%= render 'form_new', user: @user %>
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-3 no-padding">
    <div class="nav-side-menu text-center">
      <img src="<%= gravatar_for @user,size: 150 %>" alt="profile" class="img-thumbnail">
      <p>
        <strong>Email:</strong>
        <%= @user.email %>
      </p>
      <p>
        <strong>Name:</strong>
        <%= @user.name %>
      </p>

      <p>
        <strong>Zipcode:</strong>
        <%= @user.zipcode %>
      </p>

      <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>

      <div class="menu-list text-left">
        <ul id="menu-content" class="menu-content collapse out">
          <a href="<%= "/users/" + @user.id.to_s %>">
            <li id="dashboard">

              <i class="fa fa-dashboard fa-lg"></i> Dashboard

            </li>
          </a>

          <% if @user.id == current_user.id %>
          <a href="<%= user_requests_path %>">
            <li id="requests active">
              <i class="fa fa-users fa-lg "></i><i class="glyphicon glyphicon-envelope"></i> Requests
              <% if @user.requests.where(:status => 0).count > 0 %>
              <span class="badge"><%= @user.requests.where(:status => 0).count%></span>
              <% end %>
            </li>
          </a>
          <% end %>

          <% if @user.id == current_user.id %>
          <a href="<%= edit_user_path %>">
            <li id="edit_information">

              <i class="fa fa-dashboard fa-lg"></i><i class="glyphicon glyphicon-wrench"></i> Reset Account

            </li>
          </a>
          <% end %>

          <% if @user.id == current_user.id %>
          <a href="<%= change_password_path %>">
            <li id="change_password">

              <i class="fa fa-dashboard fa-lg"></i><i class="glyphicon glyphicon-cog"></i> Change Password

            </li>
          </a>
          <% end %>


          <a href="<%= shopping_list_path %>">
            <li id="shopping_list">
              <i class="fa fa-user fa-lg"></i><i class="glyphicon glyphicon-shopping-cart"></i> Shopping List
            </li>
          </a>

          <a href="<%= user_reviews_path %>">
            <li id="reviews">

              <i class="fa fa-users fa-lg"></i><i class="glyphicon glyphicon-comment"></i> User Reviews

            </li>
          </a>

          <a href="<%= user_markets_path %>">
            <li id="market">

              <i class="fa fa-user fa-lg"></i><i class="glyphicon glyphicon glyphicon-grain"></i> User Markets

            </li>
          </a>

          <% if !isVendor(@user) and  @user.id == current_user.id %>
          <a href="<%= new_store_path %>">
            <li id="bevendor">

              <i class="fa fa-users fa-lg"></i><i class="glyphicon glyphicon-leaf"></i> Be Vendor

            </li>
          </a>
          <% elsif isVendor(@user) %>
          <a href="<%= "/stores/" + @user.vendor.store.id.to_s %>">
            <li id="bevendor">

              <i class="fa fa-users fa-lg"></i><i class="glyphicon glyphicon-leaf"></i> Go to Store

            </li>
          </a>
          <% end %>

          <a href="<%= root_path %>">
            <li>

              <i class="fa fa-dashboard fa-lg"></i><i class="glyphicon glyphicon-home"></i> Home Page

            </li>
          </a>

        </ul>
      </div>
    </div>
  </div>

  <div class="col-sm-9 no-padding">
    <div id="profile-board">
      <% if board == "edit" and @user.id == current_user.id %>
      <%= render  partial: "form_edit", locals: { user: user = @user} %>
      <% elsif board == "dashboard"%>
      <%= render  partial: "dashboard", locals: { user: @user,item: @items} %>
      <% elsif board == "shopping_list" and @user.id == current_user.id %>
      <%= render  partial: "shopping_list", locals: { user: @user,item: @items,test:@test} %>
      <% elsif board == "markets"%>
      <%= render  partial: "markets", locals: { user: @user} %>
      <% elsif board == "reviews"%>
      <%= render  partial: "reviews", locals: { user: @user} %>
      <% elsif board == "requests" and @user.id == current_user.id%>
      <%= render  partial: "requests", locals: { user: @user} %>
      <%= render  partial: "responsed_requests", locals: { user: @user} %>
      <% elsif board == "change_password" and @user.id == current_user.id%>
      <%= render  partial: "change_password", locals: { user: @user} %>
      <% end %>

    </div>
  </div>
</div>

<script>
$(function() {
  $.rails.allowAction = function(link) {
    if (!link.attr('data-confirm')) {
      return true;
    }
    $.rails.showConfirmDialog(link);
    return false;
  };
  $.rails.confirmed = function(link) {
    link.removeAttr('data-confirm');
    return link.trigger('click.rails');
  };
  return $.rails.showConfirmDialog = function(link) {
    var html, message;
    message = link.attr('data-confirm');

    html = "<div class=\"modal\" id=\"confirmationDialog\">\n  <div class=\"modal-dialog\">\n    <div class=\"modal-content\">\n      <div class=\"modal-header\">\n      <h4 class=\"modal-title\">Message<h4>\n      </div><div class = \"modal-body alert alert-danger\">\n      " + message + "</div>\n      <div class=\"modal-footer\">\n       <a data-dismiss=\"modal\" class=\"btn btn-default\">" + (link.data('cancel')) + "</a>   <a data-dismiss=\"modal\" class=\"btn btn-danger confirm\">" + (link.data('ok')) + "</a></div>\n    </div>\n  </div>\n</div>";
    $(html).modal();
    return $('#confirmationDialog .confirm').on('click', function() {
      return $.rails.confirmed(link);
    });
  };
});
</script>