config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'sessions/new'

  get 'user/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get  '/cities',  to: 'application#cities'
  delete '/logout',  to: 'sessions#destroy'

  get '/markets/:id/reviews', to: 'markets#ajax_reviews'
  get '/markets/:id/stores', to: 'markets#ajax_stores'
  get '/stores/:id/reviews', to: 'stores#ajax_reviews'
  get '/stores/:id/products', to: 'stores#ajax_products'
  get '/stores/new/markets', to: 'stores#ajax_search_markets'

  post '/market_images', to: 'market_image#ajax_create'
  post '/store_images', to: 'store_image#ajax_create'
  post '/product_images', to: 'product_image#ajax_create'

  delete '/market_images/:id', to: 'market_image#ajax_destory'
  delete '/store_images/:id', to: 'store_image#ajax_destory'
  delete '/product_images/:id', to: 'product_image#ajax_destory'

  get '/markets/:id/store_market_relationships/new', to: 'store_market_relationships#new'

  get '/search', to: 'searches#index'
  get '/users/:id/edit', to: 'users#edit'
  get '/users/:id/change_password', to: 'users#change_password', as: 'change_password'


  get '/users/:id/shopping_list', to: 'users#shopping_list', as: 'shopping_list'
  get '/users/:id/requests', to: 'users#requests', as: 'user_requests'
  get '/users/:id/markets', to: 'users#markets', as: 'user_markets'
  get '/users/:id/reviews', to: 'users#reviews', as: 'user_reviews'
  get '/users/:id/store/new', to: 'users#bevendor', as: 'bevendor'

  patch '/users/:id/update_password', to: 'users#update_password'

  get '/search/heroku', to: 'application#heroku'

  %w(404 422 500).each do |code|
    get code, to: "application#error", code: code
  end

  resources :subscriptions

  resources :markets do
    resources :stores
    resources :market_reviews
  end

  resources :stores do
    resources :products
    resources :store_reviews
  end

  resources :users do
    resources :shopping_lists
    resources :markets
    resources :store_reviews
    resources :market_reviews
    resources :requests
  end

  resources :stores do
    resources :subscriptions
  end

  resources :products do
    resources :shopping_lists
  end

  resources :shopping_lists
  resources :stores
  resources :vendors
  resources :users
  resources :market_reviews
  resources :store_reviews
  resources :store_market_relationships
  resources :requests
  resources :products

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :market
  belongs_to :store
  validates :market_id, presence: true
  validates :store_id, presence: true
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:new, :create, :edit, :update]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new(store_id: current_user.vendor.store.id,market_id: params[:market_id])
    respond_to do |format|
        format.html { render  partial: "new", locals: { request: @request }}
    end
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    @request.status = 0
    @request.open_time = 0
    @request.close_time = 0
    respond_to do |format|
      if @request.save
        format.html { redirect_to @request.market, notice: 'Application was successfully send.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { redirect_to @request.market, :flash => { :error => @request.errors.map{|k,v| "#{k} #{v}"}.join(',') }  }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    if @request.market.user.id != current_user.id
        redirect_to current_user, :flash => { :error => 'You do not have permission do this.' }
    else
      if request_params[:status] == "1"
        if StoreMarketRelationship.where(:market_id => @request.market.id,:store_id => @request.store.id).length > 0
          @request.destroy
          redirect_to current_user, notice: 'Store already in Market!'
        else
          @store_market_relationship = StoreMarketRelationship.new(:market_id => @request.market.id,
          :store_id => @request.store.id,
          :open_time => @request.open_time,
          :close_time => @request.close_time)

          if @store_market_relationship.save
            if @request.update(request_params)
              redirect_to current_user, notice: 'Request was successfully updated.'
            else
              @store_market_relationship.destroy
              redirect_to current_user, :flash => { :error => 'Request was can not be updated.'}

            end
          else
            redirect_to current_user, :flash => { :error => 'Store can not be add in market.'}
          end

        end
      else
        if @request.update(request_params)
          redirect_to current_user, notice: 'Request was successfully updated.'
        else
          redirect_to current_user, :flash => { :error => 'Request was can not be updated.'}
        end
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:open_time,:close_time,:market_id,:store_id,:status)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
  def translate_status_to_market_owner(status)
    if status == 0
      "Unread"
    elsif status == 1
      "Accepted"
    elsif status == 2
      "Refused"
    end
  end
end

app/views/requests/_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <h4 class="modal-title">Send Application</h4>
</div>
<%= form_for(request) do |f| %>
<div class="modal-body">
  <div class="form-group">
      <%= f.hidden_field :market_id, value: request.market_id  %>
      <%= f.hidden_field :store_id, value: request.store_id  %>
    <div class="row">
      <div class="col-md-6">
        <%= f.label :'Open Time'%>
        <div class="input-group bootstrap-timepicker timepicker">
          <%= f.text_field :open_time, class: "form-control",id: "request_opentime", value: get_time_from_timestamp(Market.find(request.market_id).open_time)  %>
          <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
        </div>
        <script type="text/javascript">
        $('#request_opentime').timepicker();
        </script>
      </div>
      <div class="col-md-6">
        <%= f.label :'Close Time'%>
        <div class="input-group bootstrap-timepicker timepicker">
          <%= f.text_field :close_time, class: "form-control",id: "request_closetime", value: get_time_from_timestamp(Market.find(request.market_id).close_time)  %>
          <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
        </div>
        <script type="text/javascript">
        $('#request_closetime').timepicker();
        </script>
      </div>
    </div>
  </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
  <%= f.submit "Submit", class: "btn btn-success" %>
</div>
<% end %>

app/views/requests/_new.html.erb
<%= render 'form', request: @request %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>