config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'sessions/new'

  get 'user/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get  '/cities',  to: 'application#cities'
  delete '/logout',  to: 'sessions#destroy'

  get '/markets/:id/reviews', to: 'markets#ajax_reviews'
  get '/markets/:id/stores', to: 'markets#ajax_stores'
  get '/stores/:id/reviews', to: 'stores#ajax_reviews'
  get '/stores/:id/products', to: 'stores#ajax_products'
  get '/stores/new/markets', to: 'stores#ajax_search_markets'

  post '/market_images', to: 'market_image#ajax_create'
  post '/store_images', to: 'store_image#ajax_create'
  post '/product_images', to: 'product_image#ajax_create'

  delete '/market_images/:id', to: 'market_image#ajax_destory'
  delete '/store_images/:id', to: 'store_image#ajax_destory'
  delete '/product_images/:id', to: 'product_image#ajax_destory'

  get '/markets/:id/store_market_relationships/new', to: 'store_market_relationships#new'

  get '/search', to: 'searches#index'
  get '/users/:id/edit', to: 'users#edit'
  get '/users/:id/change_password', to: 'users#change_password', as: 'change_password'


  get '/users/:id/shopping_list', to: 'users#shopping_list', as: 'shopping_list'
  get '/users/:id/requests', to: 'users#requests', as: 'user_requests'
  get '/users/:id/markets', to: 'users#markets', as: 'user_markets'
  get '/users/:id/reviews', to: 'users#reviews', as: 'user_reviews'
  get '/users/:id/store/new', to: 'users#bevendor', as: 'bevendor'

  patch '/users/:id/update_password', to: 'users#update_password'

  get '/search/heroku', to: 'application#heroku'

  %w(404 422 500).each do |code|
    get code, to: "application#error", code: code
  end

  resources :subscriptions

  resources :markets do
    resources :stores
    resources :market_reviews
  end

  resources :stores do
    resources :products
    resources :store_reviews
  end

  resources :users do
    resources :shopping_lists
    resources :markets
    resources :store_reviews
    resources :market_reviews
    resources :requests
  end

  resources :stores do
    resources :subscriptions
  end

  resources :products do
    resources :shopping_lists
  end

  resources :shopping_lists
  resources :stores
  resources :vendors
  resources :users
  resources :market_reviews
  resources :store_reviews
  resources :store_market_relationships
  resources :requests
  resources :products

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/store_market_relationship.rb
class StoreMarketRelationship < ApplicationRecord
  belongs_to :store
  belongs_to :market

  validates :open_time, presence: true
  validates :close_time, presence: true
  validates :open_time, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: :close_time }
  validates :close_time, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 604800 }
end

app/controllers/store_market_relationships_controller.rb
class StoreMarketRelationshipsController < ApplicationController
  before_action :set_store_market_relationship, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:create, :destroy]

  # GET /store_market_relationships
  # GET /store_market_relationships.json
  def index
    @store_market_relationships = StoreMarketRelationship.all
  end

  # GET /store_market_relationships/1
  # GET /store_market_relationships/1.json
  def show
  end

  # GET /store_market_relationships/new
  def new
    @store_market_relationship = StoreMarketRelationship.new(store_id: current_user.vendor.store.id,market_id: params[:market_id])
    respond_to do |format|
        format.html { render  partial: "new", locals: { store_market_relationship: @store_market_relationship }}
    end
  end

  # GET /store_market_relationships/1/edit
  def edit
  end

  # POST /store_market_relationships
  # POST /store_market_relationships.json
  def create
    @store_market_relationship = StoreMarketRelationship.new(store_market_relationship_params)
    @store_market_relationship.open_time = 0
    @store_market_relationship.close_time = 0
    respond_to do |format|
      if @store_market_relationship.save
        format.html { redirect_to @store_market_relationship.market, notice: ' successfully join the Market.' }
        format.json { render :show, status: :created, location: @store_market_relationship }
      else
        format.html { redirect_to @store_market_relationship.market, :flash => { :error => @store_market_relationship.errors.map{|k,v| "#{k} #{v}"}.join(',') }  }
        format.json { render json: @store_market_relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /store_market_relationships/1
  # PATCH/PUT /store_market_relationships/1.json
  def update
    respond_to do |format|
      if @store_market_relationship.update(store_market_relationship_params)
        format.html { redirect_to @store_market_relationship, notice: 'Store market relationship was successfully updated.' }
        format.json { render :show, status: :ok, location: @store_market_relationship }
      else
        format.html { render :edit }
        format.json { render json: @store_market_relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /store_market_relationships/1
  # DELETE /store_market_relationships/1.json
  def destroy
    @market = @store_market_relationship.market
    @store_market_relationship.destroy
    respond_to do |format|
      format.html { redirect_to @market, notice: ' successfully quit the market.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store_market_relationship
      @store_market_relationship = StoreMarketRelationship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_market_relationship_params
      params.require(:store_market_relationship).permit(:open_time,:close_time,:market_id,:store_id)
    end
end

app/helpers/store_market_relationships_helper.rb
module StoreMarketRelationshipsHelper
end

app/views/store_market_relationships/_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <h4 class="modal-title">Add New Product</h4>
</div>
<%= form_for(store_market_relationship) do |f| %>
<div class="modal-body">
  <div class="form-group">
    <%= f.hidden_field :market_id, value: store_market_relationship.market_id  %>
    <%= f.hidden_field :store_id, value: store_market_relationship.store_id  %>
    <div class="row">
      <div class="col-md-6">
        <%= f.label :'Open Time'%>
        <div class="input-group bootstrap-timepicker timepicker">
          <%= f.text_field :open_time, class: "form-control",id: "store_market_relationship_opentime", value: get_time_from_timestamp(Market.find(store_market_relationship.market_id).close_time)  %>
          <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
        </div>
        <script type="text/javascript">
        $('#store_market_relationship_opentime').timepicker();
        </script>
      </div>
      <div class="col-md-6">
        <%= f.label :'Close Time'%>
        <div class="input-group bootstrap-timepicker timepicker">
          <%= f.text_field :close_time, class: "form-control",id: "store_market_relationship_closetime", value: get_time_from_timestamp(Market.find(store_market_relationship.market_id).close_time)  %>
          <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
        </div>
        <script type="text/javascript">
        $('#store_market_relationship_closetime').timepicker();
        </script>
      </div>
    </div>
  </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
  <%= f.submit "Submit", class: "btn btn-success" %>
</div>
<% end %>

app/views/store_market_relationships/_new.html.erb
<%= render 'form', store_market_relationship: @store_market_relationship %>

app/views/store_market_relationships/edit.html.erb
<h1>Editing Store Market Relationship</h1>

<%= render 'form', store_market_relationship: @store_market_relationship %>

<%= link_to 'Show', @store_market_relationship %> |
<%= link_to 'Back', store_market_relationships_path %>

app/views/store_market_relationships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Store Market Relationships</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @store_market_relationships.each do |store_market_relationship| %>
      <tr>
        <td><%= link_to 'Show', store_market_relationship %></td>
        <td><%= link_to 'Edit', edit_store_market_relationship_path(store_market_relationship) %></td>
        <td><%= link_to 'Destroy', store_market_relationship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store Market Relationship', new_store_market_relationship_path %>

app/views/store_market_relationships/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_store_market_relationship_path(@store_market_relationship) %> |
<%= link_to 'Back', store_market_relationships_path %>